version: '3'

default: ['build']

tasks:
  default:
    desc: "Alias to run build"
    deps: [build]
  build:
    desc: "Compile the LaTeX report with XeLaTeX"
    cmds:
      - rm -f *.aux *.bbl *.bcf *.blg *.log *.run.xml *.toc *.out *.lof *.lot *.synctex.gz
      - xelatex -interaction=nonstopmode rapport.tex
      - xelatex -interaction=nonstopmode rapport.tex
    dir: .

  view:
    desc: "Open the generated PDF (depends on build)"
    deps: [build]
    cmds:
      - xdg-open rapport.pdf

  clean:
    desc: "Remove build artefacts"
    cmds:
      - rm -f *.aux *.bbl *.bcf *.blg *.log *.run.xml *.toc *.out *.lof *.lot *.synctex.gz

